name: Build Android APK (Flet)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodingizni olish
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python o‘rnatish
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Python kutubxonalarini o‘rnatish
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      # 4. Flet APK qurish
      - name: Build APK
        run: |
          flet build apk -v

      # 5. Tayyor APK’ni artifact sifatida yuklab qo‘yish
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/**/**/*.apk
